name: Metrics
on:
  schedule: 
    - cron: '0 0 * * *' # This runs daily at midnight UTC
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity
          plugin_languages: yes
          plugin_stars: yes
          plugin_commits: yes
