name: Metrics
on:
  schedule: 
    - cron: '0 0 * * *' # This runs daily at midnight UTC
  workflow_dispatch: 
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: cypheroxide/metrics@latest
        with:
          token: ${{ secrets.README_TOKEN }}
          template: classic
          base: header, activity
          plugin_languages: yes
          plugin_stars: yes
          plugin_commits: yes
